// This file is automatically generated by coin_info.py -- DO NOT EDIT!

#ifndef __COIN_INFO_H__
#define __COIN_INFO_H__

#include "coins.h"

#define COINS_COUNT (27)

extern const CoinInfo coins[COINS_COUNT];

#endif